version: '3.7'

services:

  db:
    image: postgres:12
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postges_data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # Map your host's 5434 to the container's 5432

  web:
    build: .
    container_name: todo-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      # - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - db
    volumes:
      - .:/app #maps the current project directory (.) to the container's /app directory.


volumes:
  postges_data:

